name: Auto Remediate Drift

on:
  workflow_dispatch:

jobs:
  remediate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply (ALWAYS RUN)
        run: terraform apply -auto-approve
